#! /bin/sh

# Start and stop the Box Backup client daemon.

test -x /usr/local/bin/bbackupd || exit 0
test -f /etc/box/bbackupd.conf || exit 0

case $1 in
	start)
		echo -n "Starting Box Backup Client daemon: bbackupd"
		start-stop-daemon --start --quiet --exec /usr/local/bin/bbackupd > /dev/null
		echo "."
		;;
		
	stop)
		echo -n "Stopping Box Backup Client daemon: bbackupd"
		start-stop-daemon --stop --quiet --pidfile /var/run/bbackupd.pid --exec /usr/local/bin/bbackupd
		echo "."
		;;
	
	reload|force-reload)
		echo -n "Reloading the Box Backup Client daemon's configuration"
		start-stop-daemon --stop --signal 1 --quiet --oknodo --pidfile /var/run/bbackupd.pid --exec /usr/local/bin/bbackupd
		echo "."
		;;
		
	restart)
		echo -n "Restarting the Box Backup Client daemon: bbackupd"	
		start-stop-daemon --stop --quiet --pidfile /var/run/bbackupd.pid --exec /usr/local/bin/bbackupd
		start-stop-daemon --start --quiet --exec /usr/local/bin/bbackupd > dev/null
		echo "."
		;;
	*)
		echo "Usage: /etc/init.d/bbackupd {start|stop|reload|force-reload|restart}"
		exit 1
esac

exit 0
