
MAKEEXCEPTION = ../../lib/common/makeexception.pl

# AUTOGEN SEEDING
autogen_CompressException.h autogen_CompressException.cpp:	$(MAKEEXCEPTION) CompressException.txt
	$(_PERL) $(MAKEEXCEPTION) CompressException.txt

