
MAKEPROTOCOL = ../../lib/server/makeprotocol.pl

GEN_CMD = $(MAKEPROTOCOL) testprotocol.txt

# AUTOGEN SEEDING
autogen_TestProtocol.cpp:	$(MAKEPROTOCOL) testprotocol.txt
	$(_PERL) $(GEN_CMD)

autogen_TestProtocolServer.h:	$(MAKEPROTOCOL) testprotocol.txt
	$(_PERL) $(GEN_CMD)

