MAKEPROTOCOL = ../../lib/server/makeprotocol.pl

GEN_CMD = $(MAKEPROTOCOL) backupprotocol.txt

# AUTOGEN SEEDING
autogen_BackupProtocol.cpp autogen_BackupProtocol.h:	$(MAKEPROTOCOL) backupprotocol.txt
	$(_PERL) $(GEN_CMD)


MAKEEXCEPTION = ../../lib/common/makeexception.pl

# AUTOGEN SEEDING
autogen_BackupStoreException.h autogen_BackupStoreException.cpp:	$(MAKEEXCEPTION) BackupStoreException.txt
	$(_PERL) $(MAKEEXCEPTION) BackupStoreException.txt

