link-extra: \
	../../bin/bbackupd/BackupClientContext.o \
	../../bin/bbackupd/BackupClientDeleteList.o \
	../../bin/bbackupd/BackupClientDirectoryRecord.o \
	../../bin/bbackupd/Win32BackupService.o \
	../../bin/bbackupd/BackupClientInodeToIDMap.o \
	../../bin/bbackupd/Win32ServiceFunctions.o \
	../../bin/bbackupd/BackupDaemon.o \
	../../bin/bbstored/BBStoreDHousekeeping.o \
	../../lib/backupstore/HousekeepStoreAccount.o \
	../../lib/backupstore/autogen_BackupProtocol.o \
	../../lib/backupstore/BackupStoreContext.o \
	../../lib/backupstore/BackupCommands.o \
	../../bin/bbstored/BackupStoreDaemon.o \
	../../bin/bbackupquery/BackupQueries.o \
	../../bin/bbackupquery/CommandCompletion.o \
	../../bin/bbackupquery/autogen_Documentation.o
