link-extra: ../../bin/bbackupd/autogen_ClientException.o \
	../../bin/bbackupd/BackupClientContext.o \
	../../bin/bbackupd/BackupClientDeleteList.o \
	../../bin/bbackupd/BackupClientDirectoryRecord.o \
	../../bin/bbackupd/Win32BackupService.o \
	../../bin/bbackupd/BackupClientInodeToIDMap.o \
	../../bin/bbackupd/Win32ServiceFunctions.o \
	../../bin/bbackupd/BackupDaemon.o \
	../../bin/bbstored/BBStoreDHousekeeping.o \
	../../bin/bbstored/HousekeepStoreAccount.o \
	../../lib/backupstore/autogen_BackupProtocolServer.o \
	../../lib/backupstore/BackupStoreContext.o \
	../../lib/backupstore/BackupCommands.o \
	../../bin/bbstored/BackupStoreDaemon.o
