
MAKEEXCEPTION = ../../lib/common/makeexception.pl

# AUTOGEN SEEDING
autogen_RaidFileException.h autogen_RaidFileException.cpp:	$(MAKEEXCEPTION) RaidFileException.txt
	$(PERL) $(MAKEEXCEPTION) RaidFileException.txt

