
MAKEPROTOCOL = ../../lib/server/makeprotocol.pl

GEN_CMD_SRV = $(MAKEPROTOCOL) Server testprotocol.txt
GEN_CMD_CLI = $(MAKEPROTOCOL) Client testprotocol.txt

# AUTOGEN SEEDING
autogen_TestProtocolServer.cpp:	$(MAKEPROTOCOL) testprotocol.txt
	perl $(GEN_CMD_SRV)

autogen_TestProtocolServer.h:	$(MAKEPROTOCOL) testprotocol.txt
	perl $(GEN_CMD_SRV)


# AUTOGEN SEEDING
autogen_TestProtocolClient.cpp:	$(MAKEPROTOCOL) testprotocol.txt
	perl $(GEN_CMD_CLI)

autogen_TestProtocolClient.h:	$(MAKEPROTOCOL) testprotocol.txt
	perl $(GEN_CMD_CLI)

