
MAKEPROTOCOL = ../../lib/server/makeprotocol.pl

GEN_CMD = $(MAKEPROTOCOL) TestProtocol.txt

# AUTOGEN SEEDING
autogen_TestProtocol.cpp:	$(MAKEPROTOCOL) TestProtocol.txt
	$(_PERL) $(GEN_CMD)

autogen_TestProtocolServer.h:	$(MAKEPROTOCOL) TestProtocol.txt
	$(_PERL) $(GEN_CMD)

